#! /usr/bin/env yml-docker-compose.sh
version: '3'

###
# Create a jena instance for building graphs for the DAMS
###
services:
  db:
    image: local-dev/glm-lightning-db
    restart: always
    environment:
      - POSTGRES_USER=glm
      - POSTGRES_PASS=glm
      - POSTGRES_DB=glm
    volumes:
      - db:/var/lib/postgresql/data
      - ./csv:/csv
      - ./docker/db/initdb.d/:/foo
#      - ./docker/db/initdb.d/:/docker-db-initdb.d
    ports:
      - 5432:5432

volumes:
  db:
    driver: local
